### ISSUE TITLE
Pin dependency versions

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/Access-Tool#2]
The current `requirements.txt` does not include any library versions. I believe it is best if you do (pip can generate such a file automatically).

Also, given we have a `requirements.txt` file, it makes sense to tell the user to use `pip install -r requirements.txt` in the README.

**Comment by Jaso5** [comment]
I have pinned the dependency versions (https://github.com/Spyderisk/Access-Tool/commit/79a28103a06a7b7e55706bdf63c60e8aeb4df3e0)
The readme has also been ammended (https://github.com/Spyderisk/Access-Tool/commit/7772a80984946791b020036cdd8e08f6dd3ed34f)
